version: "3.8"
services:
  mysqldb:
    image: "mysql:8.0.30"
    restart: always
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=pd
      - MYSQL_DATABASE=blogloo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=pd

  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - 6379:6379
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysqldb
      - redis
