name: pre-merge-actions
run-name: ${{ github.actor }} pre-merge actions
on:
  pull_request:
    types: [opened, reopened]
jobs:
  maven-test:
    if: github.ref_name != qdev-*
    name: maven-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          cache: maven
      - name: Test with Maven
        run: mvn --batch-mode --update-snapshots test
  ui-lint:
    if: github.ref_name != qdev-*
    name: ui-lint
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up node 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
          cache: 'yarn'
          cache-dependency-path: './web-client/yarn.lock'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run eslint
        run: yarn lint
  ui-unit-test:
    if: github.ref_name != qdev-*
    name: ui-unit-test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web-client
    steps:
      - uses: actions/checkout@v3
      - name: Set up node 16.17.1
        uses: actions/setup-node@v3
        with:
          node-version: '16.17.1'
          cache: 'yarn'
          cache-dependency-path: './web-client/yarn.lock'
      - name: Install modules
        run: yarn install --frozen-lockfile
      - name: Run test
        run: yarn test
